### ISSUE TITLE
Actividad 7-hernandez Matra Jorge Luis 

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-7-JORGELUIS2266#1]
![20221024_105424_0000](https://user-images.githubusercontent.com/112587421/197619202-13286bb5-7c1d-4c05-aabb-6b24b9840455.png)

**Comment by Daisy-GonzalezLita12** [comment]
Hola compañero muy bien hecho 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
